WFU/urls.py
from django.contrib import admin
from django.contrib.auth.views import LoginView
from django.urls import path, include
from django.contrib.auth import views as auth_views


from riddles import views
from django.views.generic import TemplateView
from django.contrib.auth.views import LogoutView
from riddles.views import login, employerAccount, jobSeekerAccount, add_vacancy, register, add_resume, logout, \
    vacancy_detail, resume_detail, chat_view, send_message, apply_vacancy, apply_resume, view_vacancy, edit_vacancy, \
    delete_vacancy, chat_list, jobseeker_applications, jobseeker_jobs, employer_applications, employer_candidates, \
    change_candidate_status, change_job_status

urlpatterns = [
    path("", views.index, name='index'),
    path("admin/", admin.site.urls),
    path('login/', login, name='login'),
    path('register/', register, name='register'),
    path('employerAccount/', employerAccount, name='employerAccount'),
    path('jobSeekerAccount/', jobSeekerAccount, name='jobSeekerAccount'),
    path('add_vacancy/', add_vacancy, name='add_vacancy'),
    path('add_resume/', add_resume, name='add_resume'),
    path('logout/', logout, name='logout'),
    path('vacancy/<int:vacancy_id>/', vacancy_detail, name='vacancy_detail'),
    path('resume/<int:resume_id>/', resume_detail, name='resume_detail'),
    path('chat/<int:other_user_id>/', chat_view, name='chat_view'),
    path('send_message/<int:other_user_id>/', views.send_message, name='send_message'),
    path('apply/vacancy/<int:vacancy_id>/', apply_vacancy, name='apply_vacancy'),
    path('apply/resume/<int:resume_id>/', apply_resume, name='apply_resume'),
    path('view_vacancy/<int:vacancy_id>/', views.view_vacancy, name='view_vacancy'),
    path('vacancy/<int:vacancy_id>/edit/', edit_vacancy, name='edit_vacancy'),
    path('vacancy/<int:vacancy_id>/delete/', delete_vacancy, name='delete_vacancy'),
    path('apply/vacancy/<int:vacancy_id>/', apply_vacancy, name='apply_vacancy'),
    path('view_resume/<int:resume_id>/', views.view_resume, name='view_resume'),
    path('edit_resume/<int:resume_id>/', views.edit_resume, name='edit_resume'),
    path('delete_resume/<int:resume_id>/', views.delete_resume, name='delete_resume'),
    path('chat/list/', chat_list, name='chat_list'),
    path('chat/<int:other_user_id>/', chat_view, name='chat_view'),
    path('jobseeker/applications/', jobseeker_applications, name='jobseeker_applications'),
    path('jobseeker/jobs/', jobseeker_jobs, name='jobseeker_jobs'),
    path('employer/applications/', employer_applications, name='employer_applications'),
    path('employer/candidates/', employer_candidates, name='employer_candidates'),
    path('change_candidate_status/<int:candidate_id>/', change_candidate_status, name='change_candidate_status'),
    path('change_job_status/<int:job_id>/', change_job_status, name='change_job_status'),
]

riddles/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser, BaseUserManager


class CustomUserManager(BaseUserManager):
    def create_user(self, email, password=None, **extra_fields):
        if not email:
            raise ValueError('The Email field must be set')
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        return self.create_user(email, password, **extra_fields)

class User(AbstractUser):
    UserID = models.AutoField(primary_key=True)
    email = models.EmailField(unique=True)
    role = models.CharField(max_length=20, choices=[('Employer', 'Работодатель'), ('JobSeeker', 'Соискатель'), ('Admin', 'Администратор')])

    objects = CustomUserManager()

    def save(self, *args, **kwargs):
        # Автоматически установить имя пользователя в значение электронной почты
        self.username = self.email
        super().save(*args, **kwargs)

    def is_employer(self):
        return self.role == 'Employer'

    def is_jobseeker(self):
        return self.role == 'JobSeeker'
class Employer(models.Model):
    EmployerID = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)
    company_name = models.CharField(max_length=100)
    company_description = models.TextField()
    def __str__(self):
        return f"{self.EmployerID.email}"
class JobSeeker(models.Model):
    JobSeekerID = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)
    birthdate = models.DateField()
    education = models.TextField()
    experience = models.TextField()

    def __str__(self):
        return f"{self.JobSeekerID.email}"

class Vacancy(models.Model):
    VacancyID = models.AutoField(primary_key=True)
    employer = models.ForeignKey(Employer, on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    description = models.TextField()
    requirements = models.TextField()
    salary = models.DecimalField(max_digits=10, decimal_places=2)

    def __str__(self):
        return f"{self.title} - {self.employer.EmployerID.email} - {self.employer.company_name} - {self.salary}"


class Resume(models.Model):
    ResumeID = models.AutoField(primary_key=True)
    job_seeker = models.ForeignKey(JobSeeker, on_delete=models.CASCADE)
    profession = models.CharField(max_length=100)
    skills = models.TextField()
    experience = models.TextField()

    def __str__(self):
        return f"{self.profession} - {self.job_seeker.JobSeekerID.email}"
class ResumeApplication(models.Model):
    ApplicationID = models.AutoField(primary_key=True)
    resume = models.ForeignKey(Resume, on_delete=models.CASCADE)

    sender = models.ForeignKey(User, on_delete=models.CASCADE)
    status = models.CharField(max_length=20, choices=[('Accepted', 'Принят'), ('Rejected', 'Отклонен'), ('Pending', 'В рассмотрении')])


class VacancyApplication(models.Model):
    ApplicationID = models.AutoField(primary_key=True)
    vacancy = models.ForeignKey(Vacancy, on_delete=models.CASCADE)
    sender = models.ForeignKey(User, on_delete=models.CASCADE)
    status = models.CharField(max_length=20, choices=[('Accepted', 'Принят'), ('Rejected', 'Отклонен'), ('Pending', 'В рассмотрении')])

class Message(models.Model):
    MessageID = models.AutoField(primary_key=True)
    sender = models.ForeignKey(User, related_name='sent_messages', on_delete=models.CASCADE)
    receiver = models.ForeignKey(User, related_name='received_messages', on_delete=models.CASCADE)
    text = models.TextField()
    timestamp = models.DateTimeField(auto_now_add=True)
    is_read = models.BooleanField(default=False)

class EducationalInstitution(models.Model):
    EduInstitutionID = models.AutoField(primary_key=True)
    name = models.CharField(max_length=100)
    specialization = models.CharField(max_length=100)
    def __str__(self):
        return f"{self.name} - {self.specialization}"
class Education(models.Model):
    EducationID = models.AutoField(primary_key=True)
    resume = models.ForeignKey(Resume, on_delete=models.CASCADE)
    edu_institution = models.ForeignKey(EducationalInstitution, on_delete=models.CASCADE)
    level = models.CharField(max_length=100)
    graduation_year = models.IntegerField()

class JobCategory(models.Model):
    CategoryID = models.AutoField(primary_key=True)
    name = models.CharField(max_length=100)

riddles/views.py
from datetime import date

from django.views.decorators.http import require_POST

from .models import User, Vacancy, Resume, Employer, VacancyApplication, ResumeApplication, EducationalInstitution
from django.contrib.auth.hashers import make_password, check_password
from django.contrib.auth import login as auth_login, logout as auth_logout
from .models import User, Employer, JobSeeker, Resume, Message, Education
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse, HttpResponseBadRequest, JsonResponse
from .forms import EmployerRegistrationForm, JobSeekerRegistrationForm
from django.utils import timezone
from django.urls import reverse
from django.db.models import Q
from django.db.models import Count
from django.views import View


@login_required
def index(request):
    vacancies = Vacancy.objects.all()
    jobseekers = JobSeeker.objects.all()
    resumes = Resume.objects.all()
    context = {'vacancies': vacancies, 'resumes': resumes, 'jobseekers':jobseekers, 'current_user': request.user}
    return render(request, 'index.html', context)

def login(request):
    if request.method == 'POST':
        email = request.POST.get('email')
        password = request.POST.get('password')

        try:
            user = User.objects.get(email=email)
        except User.DoesNotExist:
            return HttpResponse("Invalid login credentials!")

        if check_password(password, user.password):
            auth_login(request, user)
            context = {'current_user': request.user}
            if user.role == 'Admin':
                return redirect('adminAccount')
            elif user.role == 'Employer':
                return render(request, 'employerAccount.html', context)
            elif user.role == 'JobSeeker':
                return render(request, 'jobSeekerAccount.html', context)
        else:
            print("Authentication failed")
            return HttpResponse("Invalid login credentials!")

    return render(request, "login.html")

@login_required
def logout(request):
    auth_logout(request)
    return redirect('index')

def register(request):
    if request.method == 'POST':
        role = request.POST.get('role')

        if role == 'Employer':
            form = EmployerRegistrationForm(request.POST)
        elif role == 'JobSeeker':
            form = JobSeekerRegistrationForm(request.POST)

            # Переместите проверку валидности сюда
            if form.is_valid():
                birthdate = form.cleaned_data.get('birthdate')
                if birthdate:
                    age = (date.today() - birthdate).days // 365
                    if age < 18 or age > 65:
                        return HttpResponse("Возраст должен быть от 18 до 65 лет")
        else:
            return HttpResponse("Недопустимая роль")

        # Переместите проверку form.is_valid() сюда
        if form.is_valid():
            user = form.save(commit=False)
            user.email = form.cleaned_data['email']
            user.set_password(form.cleaned_data['password1'])
            user.save()

            if role == 'Employer':
                employer = Employer(EmployerID=user,
                                    company_name=request.POST['company_name'],
                                    company_description=request.POST['company_description'])
                employer.save()
            elif role == 'JobSeeker':
                jobseeker = JobSeeker(JobSeekerID=user,
                                      birthdate=request.POST['birthdate'])
                jobseeker.save()

            context = {'current_user': user}
            return render(request, 'login.html', context)
    else:
        form = EmployerRegistrationForm()

    return render(request, 'register.html', {'form': form})
@login_required
def employerAccount(request):
    context = {'current_user': request.user}
    return render(request, 'employerAccount.html', context)

@login_required
def jobSeekerAccount(request):
    context = {'current_user': request.user}
    return render(request, 'jobSeekerAccount.html', context)

@login_required
def add_vacancy(request):
    # Проверяем, является ли пользователь работодателем
    if request.user.role != 'Employer':
        print("Пользователь не является работодателем. Доступ запрещен.")
        return HttpResponse("Вы не авторизованы для добавления вакансий.")
    employer = request.user.employer
    # Ваш остальной код добавления вакансии
    if request.method == 'POST':
        # Обработка добавления вакансии
        new_vacancy = Vacancy(
            employer=employer,
            title=request.POST['title'],
            description=request.POST['description'],
            requirements=request.POST['requirements'],
            salary=request.POST['salary']
        )
        new_vacancy.save()
        return render(request, 'employerAccount.html')

    # Возвращаем форму добавления вакансии (GET запрос)
    return render(request, 'add_vacancy.html', context={'current_user': request.user})

@login_required
def add_resume(request):
    # Проверяем, является ли пользователь работодателем
    if request.user.role != 'JobSeeker':
        print("Пользователь не является соискателем. Доступ запрещен.")
        return HttpResponse("Вы не авторизованы для добавления вакансий.")
    job_seeker = request.user.jobseeker
    # Ваш остальной код добавления вакансии
    if request.method == 'POST':
        # Обработка добавления вакансии
        new_resume = Resume(
            job_seeker=job_seeker,
            profession=request.POST['profession'],
            skills=request.POST['skills'],
            experience=request.POST['experience'],

        )
        new_resume.save()
        education = Education(
            resume=new_resume,
            edu_institution=EducationalInstitution.objects.get(pk=request.POST['edu_institution']),
            level=request.POST['edu_level'],
            graduation_year=request.POST['graduation_year'],
        )
        education.save()

        return render(request, 'jobSeekerAccount.html')

        # Получение данных для выпадающего списка учебных учреждений
    edu_institutions = EducationalInstitution.objects.all()

    # Возвращаем форму добавления резюме (GET запрос)
    return render(request, 'add_resume.html', context={'current_user': request.user, 'edu_institutions': edu_institutions})

@login_required
def vacancy_detail(request, vacancy_id):
    # Retrieve the vacancy using the vacancy_id
    vacancy = get_object_or_404(Vacancy, pk=vacancy_id)
    employer = vacancy.employer
    # Pass the vacancy to the template context
    applications = VacancyApplication.objects.filter(vacancy=vacancy, sender=request.user)
    context = {'vacancy': vacancy, 'current_user': request.user, 'employer': employer, 'applications': applications}

    return render(request, 'vacancy_detail.html', context)


@login_required
def resume_detail(request, resume_id):
    resume = get_object_or_404(Resume, pk=resume_id)
    job_seeker = resume.job_seeker
    education = Education.objects.filter(resume=resume)
    applications = ResumeApplication.objects.filter(resume=resume, sender=request.user)
    context = {'resume': resume, 'current_user': request.user, 'job_seeker': job_seeker, 'education': education,
               'applications': applications, 'user': request.user}

    return render(request, 'resume_detail.html', context)

@login_required
def chat_view(request, other_user_id):
    try:
        other_user = get_object_or_404(User, UserID=other_user_id)
    except User.DoesNotExist:
        return HttpResponseBadRequest("User not found")

    chat_messages = Message.objects.filter(
        (Q(sender=request.user) & Q(receiver=other_user)) |
        (Q(sender=other_user) & Q(receiver=request.user))
    ).order_by('timestamp')

    if other_user.role == 'Employer':
        employer = get_object_or_404(Employer, EmployerID=other_user)
        context = {'other_user': employer, 'other_user_id': other_user_id, 'chat_messages': chat_messages, 'user': request.user}
    elif other_user.role == 'JobSeeker':
        job_seeker = get_object_or_404(JobSeeker, JobSeekerID=other_user)
        context = {'other_user': job_seeker, 'other_user_id': other_user_id, 'chat_messages': chat_messages, 'user': request.user}
    else:
        return HttpResponseBadRequest("Invalid user type")

    return render(request, 'chat.html', context)

@login_required
@require_POST
def send_message(request, other_user_id):
    if request.method == 'POST':
        other_user_id = int(other_user_id)
        other_user = get_object_or_404(User, UserID=other_user_id)

        message_text = request.POST.get('message')

        if message_text:
            Message.objects.create(
                sender=request.user,
                receiver=other_user,
                text=message_text,
                timestamp=timezone.now()
            )

    return redirect(reverse('chat_view', kwargs={'other_user_id': other_user_id}))
@login_required
def chat_view(request, other_user_id):
    other_user = get_object_or_404(User, UserID=other_user_id)
    chat_messages = Message.objects.filter(
        (Q(sender=request.user, receiver=other_user) | Q(sender=other_user, receiver=request.user)),
    ).order_by('timestamp')

    context = {'other_user': other_user, 'other_user_id': other_user_id, 'chat_messages': chat_messages}
    return render(request, 'chat.html', context)
@login_required
def chat_list(request):
    user_chats_sender = Message.objects.filter(
        sender=request.user
    ).values('receiver').annotate(num_unread=Count('MessageID', filter=Q(is_read=False)))

    user_chats_receiver = Message.objects.filter(
        receiver=request.user
    ).values('sender').annotate(num_unread=Count('MessageID', filter=Q(is_read=False)))

    user_chats = user_chats_sender.union(user_chats_receiver)

riddles/templates/add_resume.html
{% extends 'index.html' %}

{% block content %}
    <style>
        /* Стили для всплывающего окна предупреждения */
        #warning-popup {
            display: none;
            position: fixed;
            top: 50%;
            left: 50%;
            transform: translate(-50%, -50%);
            padding: 20px;
            background-color: #fff;
            border: 1px solid #ccc;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.5);
            z-index: 1000;
        }
         h2 {
        color: rgb(255, 193, 7);
    }

    input {
        width: 100%;
        padding: 10px;
        margin: 8px 0;
        box-sizing: border-box;
        border: 1px solid #ccc;
        border-radius: 4px;
        outline: none;
    }

    input:focus {
        border-color: rgb(255, 193, 7);
    }
    textarea {
        width: 100%;
        padding: 10px;
        margin: 8px 0;
        box-sizing: border-box;
        border: 1px solid #ccc;
        border-radius: 4px;
        outline: none;
    }

    textarea:focus {
        border-color: rgb(255, 193, 7);
    }

    button {
        background-color: rgb(255, 193, 7);
        color: white;
        padding: 10px 15px;
        border: none;
        border-radius: 4px;
        cursor: pointer;
        transition: background-color 0.3s;
    }

    button:hover {
        background-color: #ffaa00;
    }

    a {
        text-decoration: none;
        color: rgb(255, 193, 7);
        /*display: block;*/
        margin-top: 10px;
    }
    </style>
  <h2>Add Resume</h2>


  <form method="post" action="{% url 'add_resume' %}">
    {% csrf_token %}


    <input type="text" id="profession" name="profession" placeholder="Профессия/Специализация" required>
    <br>

    <textarea id="skills" name="skills" rows="4" placeholder="Навыки" required></textarea>
    <br>

    <textarea id="experience" name="experience" rows="4" placeholder="Опыт работы" required></textarea>
    <br>
      <select id="edu_institution" name="edu_institution" required>
        {% for institution in edu_institutions %}
            <option value="{{ institution.EduInstitutionID }}">{{ institution.name }} - {{ institution.specialization }}</option>{% endfor %}
      </select>
    <br>

    <input type="text" id="edu_level" name="edu_level" placeholder="Уровень образования" required>
    <br>

    <input type="number" id="graduation_year" name="graduation_year" placeholder="Год окончания" required>
    <br>


    <button type="submit" onclick="return validateForm()">Add Resume</button>
  </form>

  {% if warning %}
<div id="warning-popup">
    <p>User has no employer. Please contact support.</p>
</div>
{% endif %}
{% endblock %}

riddles/templates/delete_resume.html
{% extends "index.html" %}
{% block title %}Удаление резюме{% endblock title %}
{% block header %}Удаление резюме{% endblock header %}

{% block content %}
<style>
  button {
        background-color: rgb(255, 193, 7);
        color: white;
        padding: 10px 15px;
        border: none;
        border-radius: 4px;
        cursor: pointer;
        transition: background-color 0.3s;
    }

    button:hover {
        background-color: #ffaa00;
    }
</style>

  <p>Вы уверены, что хотите удалить резюме "{{ resume.profession }}"?</p>
  <form method="post">
    {% csrf_token %}
    <button type="submit">Да, удалить</button>
  </form>
{% endblock content %}

riddles/templates/employerAccount.html
{% extends "index.html" %}
{% block title %}Личный кабинет{% endblock title %}
{% block header %}Привет, работодатель!{% endblock header %}
  
{% block content %}
<style>
    body {
        font-family: Arial, sans-serif;
        background-color: #f4f4f4;
        color: #333;
        margin: 0;
        padding: 0;
    }

    .dashboard-links {
        margin-bottom: 20px;
    }

    .dashboard-links a {
        display: inline-block;
        margin-right: 20px;
        text-decoration: none;
        color: #333;
        font-weight: bold;
        padding: 10px 15px;
        border: 1px solid #333;
        border-radius: 5px;
        transition: color 0.3s, border-color 0.3s;
    }

    .dashboard-links a:hover {
        color: #fff;
        background-color: #333;
    }

    .resume-list {
        list-style-type: none;
        padding: 0;
    }

    .resume-item {
        background-color: #fff;
        border: 1px solid #ccc;
        border-radius: 8px;
        margin-bottom: 10px;
        padding: 10px;
    }

    .profession {
        font-size: 18px;
        font-weight: bold;
        color: #333;
    }

    .resume-actions a {
        margin-right: 10px;
        text-decoration: none;
        color: #666;
        font-size: 14px;
        transition: color 0.3s;
    }

    .resume-actions a:hover {
        color: #f90;
    }
</style>


<div class="dashboard-links">
    <a href="{% url 'add_vacancy' %}">Добавить вакансию</a>
    <a href="{% url 'employer_applications' %}">Мои отклики на резюме</a>
    <a href="{% url 'employer_candidates' %}">Мои кандидаты на вакансии</a>
</div>

<h2>Мои вакансии</h2>
<ul class="resume-list">
    {% for vacancy in current_user.employer.vacancy_set.all %}
        <li class="resume-item">
            <span class="profession">{{ vacancy.title }}</span>
            <div class="resume-actions">
                <a href="{% url 'view_vacancy' vacancy_id=vacancy.VacancyID %}">Просмотр</a>
                <a href="{% url 'edit_vacancy' vacancy_id=vacancy.VacancyID %}">Редактировать</a>
                <a href="{% url 'delete_vacancy' vacancy_id=vacancy.VacancyID %}">Удалить</a>
            </div>
        </li>
    {% endfor %}
</ul>
</div>
{% endblock content %}

riddles/templates/employer_candidates.html
{% extends "index.html" %}
{% block title %}Кандидаты{% endblock title %}
{% block header %}Кандидаты на работу{% endblock header %}

{% block content %}

<style>
  body {
    font-family: Arial, sans-serif;
    background-color: #f4f4f4;
    color: #333;
    margin: 0;
    padding: 0;
  }

  h2 {
    color: rgb(255, 193, 7);
  }

  ul {
    list-style-type: none;
    padding: 0;
  }

  li {
    background-color: #fff;
    border: 1px solid #ccc;
    border-radius: 8px;
    margin-bottom: 15px;
    padding: 15px;
  }

  h3 {
    color: rgb(255, 193, 7);
  }

  p {
    margin: 8px 0;
  }

  form {
    margin-top: 15px;
  }

  select, button {
    padding: 8px;
    margin-right: 10px;
  }

  button {
    background-color: rgb(255, 193, 7);
    color: #fff;
    border: none;
    border-radius: 4px;
    cursor: pointer;
    transition: background-color 0.3s;
  }

  button:hover {
    background-color: #ff8800;
  }
</style>

{% if candidates %}
  <ul>
    {% for candidate in candidates %}
      <li>
        <h3>Претендует на вакансию: {{ candidate.vacancy.title }}</h3>
        <p>{{ candidate.sender.first_name }} {{ candidate.sender.last_name }}</p>
        <p>Статус: {{ candidate.get_status_display }}</p>

        <!-- Form for changing the status -->
         <form method="post" action="{% url 'change_candidate_status' candidate_id=candidate.ApplicationID %}">
          {% csrf_token %}
          <select name="new_status">
            <option value="Accepted">Принять</option>
            <option value="Rejected">Отклонить</option>
            <option value="Pending">В рассмотрении</option>
          </select>
          <button type="submit">Изменить статус</button>
        </form>
      </li>
    {% endfor %}
  </ul>
{% else %}
  <p>У вас нет кандидатов на работу.</p>
{% endif %}
{% endblock content %}

riddles/templates/empployerAccount.html
{% extends "index.html" %}
{% block title %}Личный кабинет{% endblock title %}
{% block header %}привет работодатель{% endblock header %}
  
{% block content %}
<p>Телефон: +12345677890</p>
<p>Email: admin@admin.com</p>
{% endblock content %}

riddles/templates/jobSeekerAccount.html
{% extends "index.html" %}
{% block title %}Личный кабинет{% endblock title %}
{% block header %}Привет, соискатель!{% endblock header %}

{% block content %}
<style>
    body {
        font-family: Arial, sans-serif;
        background-color: #f4f4f4;
        color: #333;
        margin: 0;
        padding: 0;
    }

    .dashboard-links {
        margin-bottom: 20px;
    }

    .dashboard-links a {
        display: inline-block;
        margin-right: 20px;
        text-decoration: none;
        color: #333;
        font-weight: bold;
        padding: 10px 15px;
        border: 1px solid #333;
        border-radius: 5px;
        transition: color 0.3s, border-color 0.3s;
    }

    .dashboard-links a:hover {
        color: #fff;
        background-color: #333;
    }

    .resume-list {
        list-style-type: none;
        padding: 0;
    }

    .resume-item {
        background-color: #fff;
        border: 1px solid #ccc;
        border-radius: 8px;
        margin-bottom: 10px;
        padding: 10px;
    }

    .profession {
        font-size: 18px;
        font-weight: bold;
        color: #333;
    }

    .resume-actions a {
        margin-right: 10px;
        text-decoration: none;
        color: #666;
        font-size: 14px;
        transition: color 0.3s;
    }

    .resume-actions a:hover {
        color: #f90;
    }
</style>

<div class="dashboard-links">
    <a href="/add_resume">Добавить резюме</a>
    <a href="{% url 'jobseeker_applications' %}">Мои отклики на вакансии</a>
    <a href="{% url 'jobseeker_jobs' %}">Мои предложения</a>
</div>

<h2>Мои резюме</h2>
<ul class="resume-list">
    {% for resume in current_user.jobseeker.resume_set.all %}
        <li class="resume-item">
            <span class="profession">{{ resume.profession }}</span>
            <div class="resume-actions">
                <a href="{% url 'view_resume' resume_id=resume.ResumeID %}">Просмотр</a>
                <a href="{% url 'edit_resume' resume_id=resume.ResumeID %}">Редактировать</a>
                <a href="{% url 'delete_resume' resume_id=resume.ResumeID %}">Удалить</a>
            </div>
        </li>
    {% endfor %}
</ul>
</div>
{% endblock content %}

riddles/templates/jobseeker_jobs.html
{% extends "index.html" %}
{% block title %}Мои работы{% endblock title %}
{% block header %}Мои предложения о работе{% endblock header %}

{% block content %}
<style>
  body {
    font-family: Arial, sans-serif;
    background-color: #f4f4f4;
    color: #333;
    margin: 0;
    padding: 0;
  }

  h2 {
    color: rgb(255, 193, 7);
  }

  ul {
    list-style-type: none;
    padding: 0;
  }

  li {
    background-color: #fff;
    border: 1px solid #ccc;
    border-radius: 8px;
    margin-bottom: 15px;
    padding: 15px;
  }

  h3 {
    color: rgb(255, 193, 7);
  }

  p {
    margin: 8px 0;
  }

  form {
    margin-top: 15px;
  }

  select, button {
    padding: 8px;
    margin-right: 10px;
  }

  button {
    background-color: rgb(255, 193, 7);
    color: #fff;
    border: none;
    border-radius: 4px;
    cursor: pointer;
    transition: background-color 0.3s;
  }

  button:hover {
    background-color: #ff8800;
  }
</style>

  <h2>Мои работы</h2>
  {% if job_applications %}
    <ul>
        {% for job_application in job_applications %}
            <li>
                <h3>{{ job_application.vacancy.title }}</h3>
                <p>Company: {{ job_application.vacancy.employer.company_name }}</p>
                <p>Salary: {{ job_application.vacancy.salary }}</p>
                <p>Status: {{ job_application.get_status_display }}</p>

                <!-- Form for changing the status -->
                <form method="post" action="{% url 'change_job_status' job_id=job_application.ApplicationID %}">
                    {% csrf_token %}
                    <select name="new_status">
                        <option value="Accepted">Accept</option>
                        <option value="Rejected">Reject</option>
                        <option value="Pending">Pending</option>
                    </select>
                    <button type="submit">Change Status</button>
                </form>
            </li>
            {# Добавьте отладочные выводы #}
            {{ job_application.vacancy.title }}
            {{ job_application.vacancy.employer.company_name }}
            {{ job_application.vacancy.salary }}
        {% endfor %}
    </ul>
  {% else %}
    <p>У вас нет предложенных вакансий.</p>
  {% endif %}
{% endblock content %}